// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NSFreeway.Contexts;

#nullable disable

namespace NSFreeway.Migrations
{
    [DbContext(typeof(HighwayContext))]
    partial class HighwayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("NSFreeway.Models.HighwayModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BeginCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeginState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTollRoad")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoadClass")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("RoadNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Highways");
                });
#pragma warning restore 612, 618
        }
    }
}
